const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const nodes={},calls=[],messages=[];
const $=id=>nodes[id]||(nodes[id]={value:'',disabled:false,hidden:false,innerHTML:'',showModal(){this.open=true;},close(){this.open=false;}});
let refreshes=0;
const ctx={$,esc:s=>String(s),encodeURIComponent,aiProjectId:'p1',aiManagerStatus:{enabled:true,summary_interval_minutes:30,schedule_revision:2,base_calls_per_day:null,max_calls_per_day:null,used_today:25},toast:s=>messages.push(s),aiRefresh:async()=>refreshes++};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function osManagerUseText('),html.indexOf('async function osAnalyze(')),ctx);
let fresh={...ctx.aiManagerStatus};
ctx.api=async(route,body)=>{calls.push({route,body});return body?{}:{...fresh};};
function open(){ctx.osManagerSettings();$('managerInterval').value='30';$('managerCustom').value='30';calls.length=0;messages.length=0;}
(async()=>{
 assert(ctx.osManagerUseText(ctx.aiManagerStatus).includes('25 次 · 不限次数'));
 assert(ctx.osManagerUseText({...ctx.aiManagerStatus,max_calls_per_day:4}).includes('旧版设置'));
 assert(ctx.osManagerCadenceText(ctx.aiManagerStatus).includes('30 分钟'));
 open();
 for(const value of ['15','30','60','custom'])assert($('form').innerHTML.includes('value="'+value+'"'));
 assert(!$('form').innerHTML.includes('managerBudget'));
 $('managerInterval').value='custom';$('managerInterval').onchange();assert.equal($('managerCustomWrap').hidden,false);
 $('managerCustom').value='17';await $('managerEnable').onclick();
 assert.equal(calls.length,3);assert.equal(calls[0].body,undefined);
 assert(calls.slice(1).every(c=>c.route==='project/manager/schedule'&&c.body.max_calls_per_day===null&&c.body.summary_interval_minutes===17&&c.body.if_schedule_revision===2));
 assert.equal(calls[1].body.dry,true);assert.equal(calls[2].body.dry,undefined);
 assert.equal(calls[2].body.enabled,undefined,'Changing frequency must not reauthorize or reset generation');
 assert.equal(refreshes,1);assert.equal($('modal').open,false);
 open();$('managerCancel').onclick();assert.equal(calls.length,0);
 open();$('managerInterval').value='custom';$('managerCustom').value='0';await $('managerEnable').onclick();assert.equal(calls.length,0);assert.equal($('managerEnable').disabled,false);
 open();fresh.schedule_revision=3;await $('managerEnable').onclick();assert.equal(calls.length,1);assert(messages.at(-1).includes('已变化'));
 fresh={...ctx.aiManagerStatus};open();ctx.aiProjectId='p2';await $('managerEnable').onclick();assert.equal(calls.length,1);ctx.aiProjectId='p1';
 open();ctx.api=async(route,body)=>{calls.push({route,body});if(body)throw new Error('conflict');return fresh;};await $('managerEnable').onclick();assert.equal(calls.length,2,'No retry or apply after failed dry check');assert.equal($('managerEnable').disabled,false);
 ctx.api=async(route,body)=>{calls.push({route,body});return body?{}:fresh;};
 ctx.aiManagerStatus={...ctx.aiManagerStatus,enabled:false};fresh={...ctx.aiManagerStatus};open();await $('managerEnable').onclick();
 assert(calls.slice(1).every(c=>c.route==='project/manager'&&c.body.enabled===true&&c.body.consent==='codex-project-records-v1'));
 calls.length=0;await ctx.osManagerPause();assert.equal(calls.length,1);assert.equal(calls[0].body.enabled,false);assert.equal(calls[0].body.max_calls_per_day,null);assert.equal(calls[0].body.summary_interval_minutes,30);
 let inspectorClick,opened=0;ctx.osManagerSettings=()=>opened++;
 $('inspector').addEventListener=(type,cb)=>inspectorClick=cb;
 const start=html.indexOf('$("inspector").addEventListener("click", function (event) {',html.indexOf('function osManagerUseText('));
 vm.runInContext(html.slice(start,html.indexOf('$("content").addEventListener("click", function (event) {',start)),ctx);
 inspectorClick({target:{closest:selector=>selector==='[data-ai-action]'?{dataset:{aiAction:'manager-settings'}}:null}});
 assert.equal(opened,1,'The connection Inspector must actually open summary settings');
 console.log('Summary settings PASS: presets/custom, unlimited display, read/dry/versioned apply, no generation reset, cancel, invalid/stale/project switch rejection, no retry, explicit enable/pause and real Inspector route');
})().catch(e=>{console.error(e);process.exit(1);});
