const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
for(const match of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);
const escape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const ctx={esc:escape,Date,osDisclosure:(label,text)=>'<details><summary>'+escape(label)+'</summary>'+escape(text)+'</details>'};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function osRegisteredCoverageMarkup('),html.indexOf('function osMountStatus(')),ctx);
vm.runInContext(html.match(/function aiTime\(value\) \{[^\n]+/)[0],ctx);
vm.runInContext(html.slice(html.indexOf('function osReadingReceiptMarkup('),html.indexOf('function osContinuityMarkup(')),ctx);
vm.runInContext(html.slice(html.indexOf('function osResultReviewReceipts('),html.indexOf('function osReadingReceiptMarkup(')),ctx);
vm.runInContext(html.slice(html.indexOf('function osSourceIndexItemMarkup('),html.indexOf('function osWorkspaceMarkup(')),ctx);
assert.equal(ctx.osReadingReceiptMarkup(null),'');
assert(ctx.osReadingReceiptMarkup({id:1}).includes('阅读范围无法确认'));
const job={analysis_context:{source_hash:'old-version',model_input_sha256:'sha256:input',source_read_receipt:{state:'current_ledger',observed_at:1790997005,batch_id:'batch-1',counts:{indexed:3,processed:2,pending:0,unsupported:1},batch_chunks:[{source_id:'file:<script>',version:'sha256:abc',chunk_start:0,chunk_end:3,processing_state:'accepted'}],conversation_sources:[{id:'thread:x',version:'sha256:thread',window:'最近20条用户/助手文本，每条最多2000字',truncated:true,filtered_sensitive_messages:2}]}}};
let out=ctx.osReadingReceiptMarkup(job);
assert(out.includes('调用时账本 · 非实时'));assert(out.includes('已处理 2'));assert(out.includes('待处理 0'));
assert(out.includes('&lt;script>'));assert(!out.includes('<script>'));assert(out.includes('回包不等于理解'));assert(!out.includes(' open'));
assert(out.includes('本批对话窗口'));assert(out.includes('内容已截断'));assert(out.includes('已过滤疑似敏感消息 2'));
assert(out.includes('输入快照：old-version'));assert(out.includes('准备输入 JSON hash：sha256:input'));
const recordsOnly=ctx.osReadingReceiptMarkup({analysis_context:{source_read_receipt:null,model_input_sha256:'sha256:records'}});
assert(recordsOnly.includes('本次只使用项目登记记录'));assert(recordsOnly.includes('sha256:records'));assert(!recordsOnly.includes('旧总结'));
assert.equal(ctx.aiTime(1790997005),ctx.aiTime(1790997005000));
assert.equal(ctx.aiTime(1790997005),ctx.aiTime('2026-10-03T03:10:05Z'));
job.analysis_context.source_read_receipt={state:'scope_or_batch_changed',batch_id:'old',counts:null,batch_chunks:[]};
out=ctx.osReadingReceiptMarkup(job);assert(out.includes('进度无法确认'));assert(!out.includes('已处理 0'));
const result={id:'r',outcome:'failure',verification_status:'UNVERIFIED',source_ref:'file:a',source_version:'v1'},context={result_reviews:[{id:'receipt-a',project_id:'p',result_id:'r',source_ref:'file:a',source_version:'v1',checked_source_version:'v1',review_kind:'software',conclusion:'accepted',criteria:'only UI refresh',reviewer:'<script>',notes:'not a scientific test'},{id:'receipt-b',project_id:'q',result_id:'r',source_ref:'file:a',source_version:'v1',review_kind:'scientific',conclusion:'accepted',criteria:'OTHER_PROJECT_MARKER'}]};
const original=JSON.stringify(result);
out=ctx.osResultReviewReceipts(result,context,'p');
assert(out.includes('软件检查 · 已接受，仅所列判据'));assert(out.includes('科学状态仍未评估'));assert(out.includes('&lt;script>'));assert(!out.includes('OTHER_PROJECT_MARKER'));assert.equal(JSON.stringify(result),original);
result.source_version='v2';out=ctx.osResultReviewReceipts(result,context,'p');assert(out.includes('收据所查来源与当前结果记录不同'));assert(out.includes('登记版本：v1'));
assert(ctx.osResultReviewReceipts(result,{},'p').includes('未返回复核收据'));
const row={reference:'/safe/<script>.md',state:'read',size:13,offset:13,accepted:1,version:'sha256:source'};
out=ctx.osSourceIndexItemMarkup(row,'local_read');assert(out.includes('本地读取完成'));assert(!out.includes('正文批次已获有效回包'));assert(out.includes('已处理字节 13 / 13'));assert(out.includes('sha256:source'));assert(!out.includes(' open'));assert(!out.includes('<script>'));
out=ctx.osSourceIndexItemMarkup(row,'model_reply');assert(out.includes('正文批次已获有效回包'));assert(!out.includes('AI已理解'));
console.log('Reading receipts UI PASS: non-live ledger, version/hash distinction, escaped sources, truncated conversation window, closed disclosure and seconds timestamps');
const elements={form:{innerHTML:'',contains:n=>n===elements.runtimeConfirm},modal:{showModal(){this.open=true;},close(){this.open=false;}},runtimeCancel:{},runtimeConfirm:{},runtimeConsent:{checked:false}};
const requests=[];
Object.assign(ctx,{data:{projects:[{id:'p',workspace:'/old-note'}]},aiProjectId:'p',aiManagerStatus:{runtime:{enabled:false,revision:0},workspace:{configured:true,path:'/bound/current',revision:2}},$:id=>elements[id],api:async(route,body)=>{requests.push({route,body});return !body?ctx.aiManagerStatus:body.dry?{preview:true,revision:0}:ctx.aiManagerStatus;},osUpdateSetupIndicators(){},aiRefresh:async()=>{},toast:()=>{}});
vm.runInContext(html.slice(html.indexOf('async function osManagerRuntime('),html.indexOf('function osResumeBriefMarkup(')),ctx);
ctx.osManagerRuntime().then(async()=>{assert(elements.form.innerHTML.includes('/bound/current'));assert(!elements.form.innerHTML.includes('/old-note'));elements.runtimeConsent.checked=true;elements.runtimeConsent.onchange();await elements.runtimeConfirm.onclick();assert.equal(requests[2].body.workspace_revision,2);assert.equal(requests[2].body.enabled,true);console.log('Runtime consent UI PASS: fresh bound directory displayed and exact binding revision sent');}).catch(error=>{console.error(error);process.exitCode=1;});
