const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = html.match(/<style id="rd-display-typography">([\s\S]*?)<\/style>/)[1];
assert(css.includes('font-display: swap;'), 'Never hide headings while the font loads');
assert(css.includes('font-synthesis: none;'), 'Use the real bundled bold face');
assert(css.includes('body { font-family: var(--rd-font-reading); }'), 'Keep evidence and data in reading type');
assert(css.includes('.rd-brand-name, .rd-title, .rd-os-project-name, .rd-dialog-title'));
assert(css.includes('.rd-brand-name small { font-family: var(--rd-font-reading);'));
assert(!/https?:/.test(css), 'No remote font request');
const bytes = fs.readFileSync(path.join(root, 'assets/fonts/ChillRoundGothic-Bold.woff'));
assert.equal(bytes.subarray(0,4).toString(), 'wOFF');
assert.equal(bytes.readUInt32BE(8), bytes.length, 'Valid complete font file');
assert(fs.readFileSync(path.join(root, 'assets/fonts/OFL.txt'), 'utf8').includes('SIL OPEN FONT LICENSE Version 1.1'));
const server = fs.readFileSync(path.join(root,'server.py'), 'utf8');
assert(server.includes("if path=='/assets/fonts/ChillRoundGothic-Bold.woff':"), 'Exact asset route, not directory exposure');
console.log('Typography PASS: bundled real rounded display face, offline loading, readable body, exact asset route, license retained');
