const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const nodes={},events=[];
const ctx={aiProjectId:'p',aiManagerStatus:{project_id:'p',workspace:{state:'needs_binding'},source_bridge:{}},aiAgents:{persistent:{enabled:true,connected:true,authenticated:true,model_selection:{ready:false}}},esc:s=>String(s??''),$:id=>nodes[id]};
vm.createContext(ctx);vm.runInContext(html.slice(html.indexOf('function osSetupMarkup('),html.indexOf('aiRenderToday = osRenderToday;')),ctx);
const dots=s=>(s.match(/class="rd-setup-dot"/g)||[]).length;
assert.equal(dots(ctx.osSetupMarkup(ctx.aiAgents.persistent,ctx.aiManagerStatus)),2);
nodes.aiSetup={innerHTML:''};nodes.agentsNav={querySelectorAll:()=>[],insertAdjacentHTML:(_,s)=>events.push(s)};
nodes.workspaceNav={querySelectorAll:()=>[],insertAdjacentHTML:(_,s)=>events.push('workspace-dot:'+s)};nodes.workspaceNavStatus={textContent:''};
ctx.osUpdateSetupIndicators();assert.equal(nodes.workspaceNavStatus.textContent,'未绑定');assert(events.some(s=>s.startsWith('workspace-dot:')));
assert(nodes.aiSetup.innerHTML.includes('data-ai-action="workspace-settings"'));assert(nodes.aiSetup.innerHTML.includes('资料范围 · 可选'));
const dotEvents=events.filter(s=>s.startsWith('workspace-dot:')).length;
ctx.osApplySetupReceipt('p','workspace',{state:'ready',revision:1,path:'/synthetic'});
assert.equal(dots(nodes.aiSetup.innerHTML),1,'Only the bound-folder dot disappears');
assert(nodes.aiSetup.innerHTML.includes('已绑定项目目录'));
assert(!ctx.aiManagerStatus.source_bridge.enabled,'Binding is not source consent');
assert.equal(nodes.workspaceNavStatus.textContent,'已绑定');assert.equal(events.filter(s=>s.startsWith('workspace-dot:')).length,dotEvents,'Bound workspace must not append a pending dot');
ctx.osApplySetupReceipt('p','model',{enabled:true,connected:true,authenticated:true,model_selection:{ready:true,selected_model:'actual'}});
assert.equal(dots(nodes.aiSetup.innerHTML),0);
ctx.osApplySetupReceipt('other','workspace',{state:'ready',path:'/wrong'});assert.equal(ctx.aiManagerStatus.workspace.path,'/synthetic');
ctx.osApplySetupReceipt('p','source',{revision:1,enabled:true,send_content:false});assert(nodes.aiSetup.innerHTML.includes('只在本机读取，未发送 AI'));
ctx.aiProjectId='other';ctx.osUpdateSetupIndicators();assert.equal(nodes.workspaceNavStatus.textContent,'尚未确认');assert(!nodes.aiSetup.innerHTML.includes('/synthetic'));assert(nodes.aiSetup.innerHTML.includes('尚未绑定项目目录'),'Another project cannot inherit the previous binding');ctx.aiProjectId='p';
assert(html.includes('id="workspaceNav"'));assert(html.includes("osWorkspaceSettings(false)"));assert(html.includes(':not(#workspaceNav)'),'Workspace entry remains available in the compact sidebar');
const ctx2={aiProjectId:'p',esc:s=>String(s??''),$:id=>nodes[id],field:()=>'',toast:s=>events.push(s),osApplySetupReceipt:(p,k,r)=>events.push(k),aiRefresh:()=>new Promise(()=>{}),api:async(p,b)=>b?{state:'ready',revision:1,path:'/synthetic'}:{revision:0}};
vm.createContext(ctx2);vm.runInContext(html.slice(html.indexOf('async function osWorkspaceSettings('),html.indexOf('async function osSourceIndex(')),ctx2);
for(const id of ['form','workspaceSave','workspaceCancel','workspacePick','workspacePreview','workspaceConfirmScope','field-workspaceRoot','field-workspaceRelative','field-workspaceName','field-workspaceExclusions'])nodes[id]={value:'',checked:false};
nodes['field-workspaceRoot'].value='/synthetic';nodes['field-workspaceRelative'].value='.';
nodes.modal={open:false,showModal(){this.open=true},close(){this.open=false}};
(async()=>{
 await ctx2.osWorkspaceSettings();nodes.workspaceConfirmScope.checked=true;
 await Promise.race([nodes.workspaceSave.onclick(),new Promise((_,reject)=>setTimeout(()=>reject(Error('Acknowledgement blocked by full refresh')),500))]);
 assert(!nodes.modal.open);assert(events.includes('workspace'));assert(events.some(s=>s.includes('目录已绑定')));
 assert(html.includes('prefers-reduced-motion:reduce'));assert(html.includes("this.textContent='正在绑定…'"));
 console.log('Setup feedback PASS: per-item dots, committed immediate feedback, optional read/send, stale project and slow-refresh guards');
})().catch(e=>{console.error(e);process.exitCode=1});
