const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const ctx={esc,osNodeAttrs:(kind,id)=>' data-os-node="'+kind+'" data-os-id="'+esc(id)+'"',osDisclosure:(label,text)=>'<details><summary>'+esc(label)+'</summary>'+esc(text)+'</details>'};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function osReviewExecutionMarkup('),html.indexOf('function osMountStatus(')),ctx);
vm.runInContext(html.slice(html.indexOf('const rdEnglish = {'),html.indexOf('(function rdLanguageController()')),ctx);
const manager={enabled:true,runtime:{enabled:true},max_calls_per_day:null,used_today:0};
const partial={id:1,state:'queued',registered_coverage:{leaf_total:5,leaf_replied:3,calls_attempted:3,parts:[]},writeback_receipt:{recorded:false}};
let s=ctx.osReviewExecutionMarkup(partial,manager,{enabled:true,authenticated:true,connected:true});
assert(s.includes('3 / 5'));assert(s.includes('等待下一批'));assert(!s.includes('打开核查报告 →'));
const finished={...partial,state:'succeeded',result_id:'r',writeback_receipt:{recorded:true,outcome:'UNKNOWN',scientific_status:'NOT_ASSESSED'},registered_coverage:{leaf_total:5,leaf_replied:5,aggregation_complete:true,calls_attempted:6}};
s=ctx.osReviewExecutionMarkup(finished,manager);assert(s.includes('核查报告已登记 · 未核验'));assert.equal((s.match(/class="done"/g)||[]).length,3);assert(s.includes('data-os-id="r"'));assert(!s.includes('科学通过'));
s=ctx.osReviewExecutionMarkup({...finished,writeback_receipt:{recorded:false}},manager);assert(s.includes('回写记录不完整'));assert(!s.includes('打开核查报告 →'));assert.equal((s.match(/class="done"/g)||[]).length,2);
s=ctx.osReviewExecutionMarkup({...finished,state:'failed'},manager);assert(s.includes('未自动重跑'));assert(!s.includes('打开核查报告 →'));
s=ctx.osReviewExecutionMarkup({...partial,state:'failed_orphaned',error:'<script>untrusted</script>'},manager);assert(s.includes('回写未确认'));assert(s.includes('&lt;script>'));assert(!s.includes('<script>'));
assert(ctx.osReviewExecutionMarkup({...partial,state:'review_ready'},manager).includes('回包已保存'));
assert(ctx.osReviewExecutionMarkup({...partial,state:'stale'},manager).includes('旧输出不用于当前判断'));
assert(ctx.osReviewExecutionMarkup({...partial,state:'cancelled'},manager).includes('不会继承新授权'));
const unknown=ctx.osReviewExecutionMarkup({...partial,state:'new_protocol_state'},manager);assert(unknown.includes('核查状态待核对'));assert(!unknown.includes('class="active"'));
assert(ctx.osReviewExecutionMarkup(partial,manager,{enabled:false}).includes('先完成 Codex 登录'));
assert(ctx.osReviewExecutionMarkup(partial,{...manager,max_calls_per_day:3,used_today:3}).includes('次数设置已用完'));
assert(ctx.osReviewExecutionMarkup({...finished,writeback_receipt:{recorded:true,source_changed:true}},manager).includes('只对应当时版本'));
const unchanged=JSON.stringify(partial);s=ctx.osReviewExecutionsMarkup({...manager,executions:[partial,finished]});assert(s.includes('更早的只读核查 · 1'));assert(!s.includes('<details open'));assert.equal(JSON.stringify(partial),unchanged);assert.equal(ctx.osReviewExecutionsMarkup(manager),'');
for(const text of ['核查报告已登记 · 未核验','核查批次回包 3 / 5','更早的只读核查 · 1',' · 已完成','只读核查批次回包','回写记录不完整 · 需要检查'])assert(!/[\u4e00-\u9fff]/.test(ctx.rdTranslateUI(text,'en')),text);
assert(html.includes('panel.innerHTML += osReviewExecutionsMarkup(manager,connection)'));
assert(html.includes('.rd-closure-label'));
console.log('PASS review progress: version-bound writeback, partial/failure/unknown, closed history, no false scientific success, escaped raw data and bilingual copy.');
