const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const ctx={esc,Date,aiTime:s=>s,aiAgentsUnavailable:false,aiProjectId:'p1',aiAgents:{agents:[]},osTreeRow:(kind,id,title,meta)=>`<button data-os-kind="${kind}" data-os-id="${esc(id)}">${esc(title)} ${esc(meta)}</button>`};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function osAgentConnectionState('),html.indexOf('function osRenderAgents()')),ctx);
const old={id:'old',name:'Codex',project_id:'p1',status:'online',connected:false,permission:'READ',last_seen:'2026-10-02T12:00:00+08:00'};
const fresh={id:'new',name:'Codex',project_id:'p1',status:'configured',connected:false,permission:'PROPOSE',last_seen:null};
assert.equal(ctx.osAgentConnectionState(null).label,'未配置');
assert.equal(ctx.osAgentConnectionState(fresh).label,'待握手');
assert.equal(ctx.osAgentConnectionState({...fresh,connected:true,last_seen:old.last_seen}).state,'unknown','Contact without handshake must not turn green');
assert.equal(ctx.osAgentConnectionState({...old,last_seen:'invalid',connected:true}).state,'unknown');
assert.equal(ctx.osAgentConnectionState(old).state,'failure');
assert(ctx.osAgentConnectionState(old).hint.includes('不等于连接失败'));
assert.equal(ctx.osAgentConnectionState({...old,connected:true}).state,'success');
ctx.aiAgents.agents=[fresh,old,{...old,id:'foreign',project_id:'p2',connected:true}];
const before=JSON.stringify(ctx.aiAgents),tree=ctx.osAgentConnectionTree();
assert(tree.includes('rd-agent-dot is-failure'));assert(!tree.includes('is-success'));assert(!tree.includes('foreign'));
assert(tree.indexOf('data-os-id="old"')<tree.indexOf('data-os-id="new"'),'Configured record must not mask the last handshaken connection');
assert(tree.includes('待握手 · PROPOSE'));assert(tree.includes('最近通信 '+old.last_seen));assert(!tree.includes(' open'));
assert.equal(JSON.stringify(ctx.aiAgents),before,'Rendering cannot alter Agent records');
ctx.aiAgents.agents.unshift({...old,id:'live',connected:true,last_seen:'2026-10-02T11:00:00+08:00'});
assert(ctx.osAgentConnectionTree().includes('rd-agent-dot is-success'));assert(ctx.osAgentConnectionTree().indexOf('data-os-id="live"')<ctx.osAgentConnectionTree().indexOf('data-os-id="old"'));
ctx.aiAgentsUnavailable=true;assert.equal(ctx.osAgentConnectionState(old).label,'状态未读取');assert(!ctx.osAgentConnectionTree().includes('is-success'));
assert(!ctx.osAgentConnectionDot({state:'unknown',label:'<script>',mark:'?',hint:'<img>'}).includes('<script>'));
assert(ctx.osAgentConnectionDot(ctx.osAgentConnectionState(old)).includes('role="img"'));
ctx.aiAgentsUnavailable=false;
const connected={configured:true,enabled:true,connected:true,authenticated:true,last_heartbeat:'2026-10-02T18:00:00+08:00',activity:'idle',state:'idle'};
assert.equal(ctx.osPersistentConnectionState(connected).label,'已连接 · 空闲');
assert.equal(ctx.osPersistentConnectionState({...connected,activity:'working'}).label,'已连接 · 执行中');
assert.equal(ctx.osPersistentConnectionState({...connected,enabled:false}).label,'已暂停');
assert.equal(ctx.osPersistentConnectionState({...connected,connected:false,state:'reconnecting'}).state,'failure');
assert.equal(ctx.osPersistentConnectionState({...connected,authenticated:false}).state,'failure');
ctx.aiAgents={agents:[old],persistent:connected};
const managedTree=ctx.osAgentConnectionTree();
assert(managedTree.includes('已连接 · 空闲'));assert(managedTree.includes('常驻管理'));assert(managedTree.includes('MCP · 最近未通信'));assert(managedTree.includes('data-ai-action="persistent-pause"'));assert(managedTree.includes('data-os-kind="connection"'));
console.log('Agent indicators PASS: real handshake, aggregate priority, neutral unknown, idle is not failure, project isolation, escaping, immutable records');

const calls=[],intervals=[],events=[];
Object.assign(ctx,{aiAgentsUnavailable:false,aiView:'agents',aiRefreshSequence:3,aiAgentPollBusy:false,window:{},encodeURIComponent,document:{visibilityState:'visible',addEventListener:(event,cb)=>events.push({event,cb})},setInterval:(cb,ms)=>intervals.push({cb,ms}),api:async(path,body)=>{calls.push({path,body});return {agents:[old]};}});
vm.runInContext(html.slice(html.indexOf('async function osPollAgentConnections()'),html.indexOf('function aiEventArrived(')),ctx);
let updates=0;ctx.osUpdateAgentConnections=()=>updates++;
(async()=>{
 await ctx.osPollAgentConnections();assert.equal(updates,1);assert(calls.every(x=>x.path==='agents?project_id=p1'&&x.body===undefined));assert.equal(intervals[0].ms,30000);
 ctx.document.visibilityState='hidden';await ctx.osPollAgentConnections();assert.equal(calls.length,1);
 ctx.document.visibilityState='visible';ctx.aiView='today';await ctx.osPollAgentConnections();assert.equal(calls.length,1);
 ctx.aiView='agents';let release;ctx.api=()=>new Promise(resolve=>release=resolve);const pending=ctx.osPollAgentConnections();await ctx.osPollAgentConnections();assert(ctx.aiAgentPollBusy);
 ctx.aiProjectId='p2';release({agents:[fresh]});await pending;assert.equal(updates,1);assert.equal(ctx.aiAgents.agents[0].id,'old');assert.equal(ctx.aiAgentPollBusy,false);
 ctx.api=async()=>{throw new Error('unavailable');};await ctx.osPollAgentConnections();assert.equal(ctx.aiAgentsUnavailable,true);assert.equal(updates,2);
 ctx.api=async()=>({agents:[]});await ctx.osPollAgentConnections();assert.equal(ctx.aiAgentsUnavailable,false);
 let releaseOld;ctx.api=()=>new Promise(resolve=>releaseOld=resolve);const oldPoll=ctx.osPollAgentConnections();ctx.aiRefreshSequence++;releaseOld({agents:[fresh]});await oldPoll;assert.equal(ctx.aiAgents.agents.length,0);
 assert.equal(events[0].event,'visibilitychange');
 ctx.aiConnectionBusy=false;const writes=[];let refreshes=0;ctx.toast=()=>{};ctx.aiRefresh=async()=>refreshes++;
 ctx.api=async(path,body)=>{writes.push({path,body});return body?{}:{revision:7,authenticated:true};};
 await ctx.osControlPersistentConnection(true);
 assert.equal(writes.length,4);assert(writes.every(x=>x.path==='agent-connection'));assert.equal(writes[1].body.dry,true);assert.equal(writes[2].body.if_revision,7);assert.equal(writes[2].body.consent,'codex-persistent-management-v1');assert.equal(refreshes,1);assert.equal(ctx.aiConnectionBusy,false);
 ctx.api=async()=>{throw new Error('stale');};await ctx.osControlPersistentConnection(false);assert.equal(refreshes,1);assert.equal(ctx.aiConnectionBusy,false);
 console.log('Agent polling PASS: GET only, visible connection view only, no overlap, stale response discarded, unread state on error and recovery');
 console.log('Persistent control PASS: connection separate from MCP activity, idle stays green, read/dry/versioned apply, no project authorization or task write, error no retry');
})().catch(e=>{console.error(e);process.exit(1)});
