const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const nodes={},calls=[],messages=[];
const $=id=>nodes[id]||(nodes[id]={disabled:false,checked:false,innerHTML:'',contains:n=>n===nodes.runtimeConfirm,showModal(){this.open=true;},close(){this.open=false;}});
const fresh={project_id:'p',runtime:{enabled:true,scope_blocked:true,revision:3},workspace:{configured:true,path:'/synthetic',revision:5}};
let onDry=null;
const ctx={$,esc:String,encodeURIComponent,aiProjectId:'p',data:{projects:[]},toast:s=>messages.push(s),osUpdateSetupIndicators(){},aiRefresh:async()=>{},api:async(route,body)=>{calls.push({route,body});if(!body)return fresh;if(body.dry){if(onDry)onDry();return {preview:true,revision:3};}return {...fresh,runtime:{enabled:body.enabled,revision:4}};}};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('async function osManagerRuntime('),html.indexOf('function osResumeBriefMarkup(')),ctx);
(async()=>{
 await ctx.osManagerRuntime('records');await $('runtimeConfirm').onclick();
 assert.equal(calls.length,3);assert.equal(calls[1].body.dry,true);assert.equal(calls[2].body.enabled,false);assert.equal(calls[2].body.if_runtime_revision,3);assert.equal(ctx.aiManagerStatus.runtime.revision,4);
 calls.length=0;await ctx.osManagerRuntime('observe');assert($('runtimeConfirm').disabled);await $('runtimeConfirm').onclick();assert.equal(calls.length,1);
 $('runtimeConsent').checked=true;$('runtimeConsent').onchange();await $('runtimeConfirm').onclick();assert.equal(calls.length,3);assert.equal(calls[2].body.workspace_revision,5);
 calls.length=0;await ctx.osManagerRuntime('records');$('runtimeCancel').onclick();await $('runtimeConfirm').onclick();assert.equal(calls.length,1);
 calls.length=0;await ctx.osManagerRuntime('records');onDry=()=>{ctx.aiProjectId='other';};await $('runtimeConfirm').onclick();assert.equal(calls.length,2,'Project switch after dry must prevent commit');
 ctx.aiProjectId='p';onDry=()=>{$('modal').close();};calls.length=0;await ctx.osManagerRuntime('records');await $('runtimeConfirm').onclick();assert.equal(calls.length,2,'Cancel during preview must prevent commit');
 assert(html.includes('data-ai-action="runtime-records"'));assert(html.includes('data-ai-action="runtime-observe"'));
 ctx.aiProjectId='p';onDry=null;fresh.input_readiness={ready:false,code:'input_too_large'};
 await ctx.osManagerRuntime('records');await $('runtimeConfirm').onclick();
 assert(messages.at(-1).includes('总结仍有阻断'),'Saving a permission must not imply a runnable summary');
 const display={esc:s=>String(s).replaceAll('<','&lt;'),osDisclosure:(title,body)=>title+body};vm.createContext(display);
 vm.runInContext(html.slice(html.indexOf('function osInputReadinessMarkup('),html.indexOf('function osMountStatus(')),display);
 const blocked=display.osInputReadinessMarkup({enabled:true,input_readiness:{ready:false,code:'input_too_large',message:'未发送模型',input_bytes:267628,limit_bytes:180000,sections:[{section:'artifacts',bytes:115617,records:181}]}});
 assert(blocked.includes('268 KB'));assert(blocked.includes('180 KB'));assert(blocked.includes('成果登记'));assert(blocked.includes('未发送模型'));
 assert.equal(display.osInputReadinessMarkup({enabled:true,input_readiness:{ready:true}}),'');
 const batched=display.osInputReadinessMarkup({enabled:true,input_readiness:{ready:true,batched:true,batch_count:5}});
 assert(batched.includes('5 批'));assert(batched.includes('全部完成前不生成行动建议'));
 assert(batched.includes('rd-closure-label'),'Batch interface copy must be enrolled in the actual locale controller');
 const partial=display.osRegisteredCoverageMarkup({state:'queued',registered_coverage:{leaf_total:5,leaf_replied:3,calls_attempted:3,parts:[]}});
 assert(partial.includes('3 / 5'));assert(partial.includes('总摘要尚未完成'));assert(!partial.includes('完整批次已汇总'));
 assert(partial.includes('<p class="rd-closure-label">'));assert(partial.includes('<small class="rd-closure-label">'));
 assert(html.includes('textarea[placeholder],.rd-ai-batch-progress progress'));
 const finished=display.osRegisteredCoverageMarkup({state:'succeeded',registered_coverage:{leaf_total:5,leaf_replied:5,aggregation_complete:true,calls_attempted:6,parts:[]}});
 assert(finished.includes('完整批次已汇总 · 仍未核验'));
 const stale=display.osRegisteredCoverageMarkup({state:'succeeded',stale:true,registered_coverage:{aggregation_complete:true,parts:[]}});
 assert(stale.includes('旧批次不用于当前判断'));assert(!stale.includes('完整批次已汇总'));
 console.log('Runtime recovery PASS: explicit record-only recovery, unchecked file consent, dry/versioned commit, receipt feedback, cancel and project switch guards');
})().catch(e=>{console.error(e);process.exit(1);});
